export const sortByOptions = [
  'Popularity Descending',
  'Popularity Ascending',
  'Rating Descending',
  'Rating Ascending',
  'Release Data Descending',
  'Release Data Ascending',
];

export const defaultOptions = {
  sortByOptions: sortByOptions[0],
  userScoreRange: [0, 10],
};

export const moviesGenres = [
  {
    id: 28,
    name: 'Action',
  },
  {
    id: 12,
    name: 'Adventure',
  },
  {
    id: 16,
    name: 'Animation',
  },
  {
    id: 35,
    name: 'Comedy',
  },
  {
    id: 80,
    name: 'Crime',
  },
  {
    id: 99,
    name: 'Documentary',
  },
  {
    id: 18,
    name: 'Drama',
  },
  {
    id: 10751,
    name: 'Family',
  },
  {
    id: 14,
    name: 'Fantasy',
  },
  {
    id: 36,
    name: 'History',
  },
  {
    id: 27,
    name: 'Horror',
  },
  {
    id: 10402,
    name: 'Music',
  },
  {
    id: 9648,
    name: 'Mystery',
  },
  {
    id: 10749,
    name: 'Romance',
  },
  {
    id: 878,
    name: 'Science Fiction',
  },
  {
    id: 10770,
    name: 'TV Movie',
  },
  {
    id: 53,
    name: 'Thriller',
  },
  {
    id: 10752,
    name: 'War',
  },
  {
    id: 37,
    name: 'Western',
  },
];

export const tvGenres = [
  {
    id: 10759,
    name: 'Action & Adventure',
  },
  {
    id: 16,
    name: 'Animation',
  },
  {
    id: 35,
    name: 'Comedy',
  },
  {
    id: 80,
    name: 'Crime',
  },
  {
    id: 99,
    name: 'Documentary',
  },
  {
    id: 18,
    name: 'Drama',
  },
  {
    id: 10751,
    name: 'Family',
  },
  {
    id: 10762,
    name: 'Kids',
  },
  {
    id: 9648,
    name: 'Mystery',
  },
  {
    id: 10763,
    name: 'News',
  },
  {
    id: 10764,
    name: 'Reality',
  },
  {
    id: 10765,
    name: 'Sci-Fi & Fantasy',
  },
  {
    id: 10766,
    name: 'Soap',
  },
  {
    id: 10767,
    name: 'Talk',
  },
  {
    id: 10768,
    name: 'War & Politics',
  },
  {
    id: 37,
    name: 'Western',
  },
];

export const moviesData = {
  page: 1,
  results: [
    {
      adult: false,
      backdrop_path: '/drulhSX7P5TQlEMQZ3JoXKSDEfz.jpg',
      genre_ids: [18, 14, 878],
      id: 581389,
      original_language: 'ko',
      original_title: '승리호',
      overview:
        "When the crew of a space junk collector ship called The Victory discovers a humanoid robot named Dorothy that's known to be a weapon of mass destruction, they get involved in a risky business deal which puts their lives at stake.",
      popularity: 2581.195,
      poster_path:
        'https://image.tmdb.org/t/p/w500/bmemsraCG1kIthY74NjDnnLRT2Q.jpg',
      release_date: '2021-02-05',
      title: 'Space Sweepers',
      video: false,
      vote_average: 7.3,
      vote_count: 219,
    },
    {
      adult: false,
      backdrop_path: '/srYya1ZlI97Au4jUYAktDe3avyA.jpg',
      genre_ids: [14, 28, 12],
      id: 464052,
      original_language: 'en',
      original_title: 'Wonder Woman 1984',
      overview:
        'Wonder Woman comes into conflict with the Soviet Union during the Cold War in the 1980s and finds a formidable foe by the name of the Cheetah.',
      popularity: 1955.44,
      poster_path:
        'https://image.tmdb.org/t/p/w500/8UlWHLMpgZm9bx6QYh0NFoq67TZ.jpg',
      release_date: '2020-12-16',
      title: 'Wonder Woman 1984',
      video: false,
      vote_average: 6.9,
      vote_count: 3718,
    },
    {
      adult: false,
      backdrop_path: '/6TPZSJ06OEXeelx1U1VIAt0j9Ry.jpg',
      genre_ids: [28, 80, 53],
      id: 587996,
      original_language: 'es',
      original_title: 'Bajocero',
      overview:
        'When a prisoner transfer van is attacked, the cop in charge must fight those inside and outside while dealing with a silent foe: the icy temperatures.',
      popularity: 1345.89,
      poster_path:
        'https://image.tmdb.org/t/p/w500/dWSnsAGTfc8U27bWsy2RfwZs0Bs.jpg',
      release_date: '2021-01-29',
      title: 'Below Zero',
      video: false,
      vote_average: 6.4,
      vote_count: 326,
    },
    {
      adult: false,
      backdrop_path: '/vfuzELmhBjBTswXj2Vqxnu5ge4g.jpg',
      genre_ids: [53, 80],
      id: 602269,
      original_language: 'en',
      original_title: 'The Little Things',
      overview:
        'Deputy Sheriff Joe "Deke" Deacon joins forces with Sgt. Jim Baxter to search for a serial killer who\'s terrorizing Los Angeles. As they track the culprit, Baxter is unaware that the investigation is dredging up echoes of Deke\'s past, uncovering disturbing secrets that could threaten more than his case.',
      popularity: 1269.182,
      poster_path:
        'https://image.tmdb.org/t/p/w500/c7VlGCCgM9GZivKSzBgzuOVxQn7.jpg',
      release_date: '2021-01-28',
      title: 'The Little Things',
      video: false,
      vote_average: 6.4,
      vote_count: 330,
    },
    {
      adult: false,
      backdrop_path: '/lOSdUkGQmbAl5JQ3QoHqBZUbZhC.jpg',
      genre_ids: [53, 28, 878],
      id: 775996,
      original_language: 'en',
      original_title: 'Outside the Wire',
      overview:
        'In the near future, a drone pilot is sent into a deadly militarized zone and must work with an android officer to locate a doomsday device.',
      popularity: 1243.196,
      poster_path:
        'https://image.tmdb.org/t/p/w500/6XYLiMxHAaCsoyrVo38LBWMw2p8.jpg',
      release_date: '2021-01-15',
      title: 'Outside the Wire',
      video: false,
      vote_average: 6.5,
      vote_count: 709,
    },
    {
      adult: false,
      backdrop_path: '/h9DIlghaiTxbQbt1FIwKNbQvEL.jpg',
      genre_ids: [28, 12, 53],
      id: 581387,
      original_language: 'ko',
      original_title: '백두산',
      overview:
        "Stagnant since 1903, at an elevation of 9000', a volcano erupts on the mythical and majestic Baekdu Mountain.",
      popularity: 1090.726,
      poster_path:
        'https://image.tmdb.org/t/p/w500/zoeKREZ2IdAUnXISYCS0E6H5BVh.jpg',
      release_date: '2019-12-19',
      title: 'Ashfall',
      video: false,
      vote_average: 6.7,
      vote_count: 191,
    },
    {
      adult: false,
      backdrop_path: '/nz8xWrTKZzA5A7FgxaM4kfAoO1W.jpg',
      genre_ids: [878, 28],
      id: 651571,
      original_language: 'en',
      original_title: 'Breach',
      overview:
        'A hardened mechanic must stay awake and maintain an interstellar ark fleeing the dying planet Earth with a few thousand lucky souls on board... the last of humanity. Unfortunately, humans are not the only passengers. A shapeshifting alien creature has taken residence, its only goal is to kill as many people as possible. The crew must think quickly to stop this menace before it destroys mankind.',
      popularity: 1031.392,
      poster_path:
        'https://image.tmdb.org/t/p/w500/13B6onhL6FzSN2KaNeQeMML05pS.jpg',
      release_date: '2020-12-17',
      title: 'Breach',
      video: false,
      vote_average: 4.6,
      vote_count: 266,
    },
    {
      adult: false,
      backdrop_path: '/fRrpOILyXuWaWLmqF7kXeMVwITQ.jpg',
      genre_ids: [27, 53, 12],
      id: 522444,
      original_language: 'en',
      original_title: 'Black Water: Abyss',
      overview:
        'An adventure-loving couple convince their friends to explore a remote, uncharted cave system in the forests of Northern Australia. With a tropical storm approaching, they abseil into the mouth of the cave, but when the caves start to flood, tensions rise as oxygen levels fall and the friends find themselves trapped. Unknown to them, the storm has also brought in a pack of dangerous and hungry crocodiles.',
      popularity: 985.346,
      poster_path:
        'https://image.tmdb.org/t/p/w500/95S6PinQIvVe4uJAd82a2iGZ0rA.jpg',
      release_date: '2020-07-09',
      title: 'Black Water: Abyss',
      video: false,
      vote_average: 5.1,
      vote_count: 135,
    },
    {
      adult: false,
      backdrop_path: '/kf456ZqeC45XTvo6W9pW5clYKfQ.jpg',
      genre_ids: [10751, 16, 35, 18, 10402, 14],
      id: 508442,
      original_language: 'en',
      original_title: 'Soul',
      overview:
        'Joe Gardner is a middle school teacher with a love for jazz music. After a successful gig at the Half Note Club, he suddenly gets into an accident that separates his soul from his body and is transported to the You Seminar, a center in which souls develop and gain passions before being transported to a newborn child. Joe must enlist help from the other souls-in-training, like 22, a soul who has spent eons in the You Seminar, in order to get back to Earth.',
      popularity: 897.045,
      poster_path:
        'https://image.tmdb.org/t/p/w500/hm58Jw4Lw8OIeECIq5qyPYhAeRJ.jpg',
      release_date: '2020-12-25',
      title: 'Soul',
      video: false,
      vote_average: 8.3,
      vote_count: 4848,
    },
    {
      adult: false,
      backdrop_path: '/fAJuZDEkrqmYQUUDrro8wRqb2Tn.jpg',
      genre_ids: [35, 18, 10749],
      id: 614409,
      original_language: 'en',
      original_title: 'To All the Boys: Always and Forever',
      overview:
        'Senior year of high school takes center stage as Lara Jean returns from a family trip to Korea and considers her college plans — with and without Peter.',
      popularity: 893.454,
      poster_path:
        'https://image.tmdb.org/t/p/w500/zdkJs9j6yKo9di0kjtctM01fSMv.jpg',
      release_date: '2021-02-12',
      title: 'To All the Boys: Always and Forever',
      video: false,
      vote_average: 8.1,
      vote_count: 764,
    },
    {
      adult: false,
      backdrop_path: '/fX8e94MEWSuTJExndVYxKsmA4Hw.jpg',
      genre_ids: [28, 12, 80],
      id: 604822,
      original_language: 'zh',
      original_title: '急先锋',
      overview:
        "Covert security company Vanguard is the last hope of survival for an accountant after he is targeted by the world's deadliest mercenary organization.",
      popularity: 873.468,
      poster_path:
        'https://image.tmdb.org/t/p/w500/vYvppZMvXYheYTWVd8Rnn9nsmNp.jpg',
      release_date: '2020-09-30',
      title: 'Vanguard',
      video: false,
      vote_average: 6.5,
      vote_count: 200,
    },
    {
      adult: false,
      backdrop_path: '/z8TvnEVRenMSTemxYZwLGqFofgF.jpg',
      genre_ids: [14, 28, 12],
      id: 458576,
      original_language: 'en',
      original_title: 'Monster Hunter',
      overview:
        'A portal transports Lt. Artemis and an elite unit of soldiers to a strange world where powerful monsters rule with deadly ferocity. Faced with relentless danger, the team encounters a mysterious hunter who may be their only hope to find a way home.',
      popularity: 869.217,
      poster_path:
        'https://image.tmdb.org/t/p/w500/uwjaCH7PiWrkz7oWJ4fcL3xGrb0.jpg',
      release_date: '2020-12-03',
      title: 'Monster Hunter',
      video: false,
      vote_average: 7,
      vote_count: 415,
    },
    {
      adult: false,
      backdrop_path: '/3ombg55JQiIpoPnXYb2oYdr6DtP.jpg',
      genre_ids: [878, 28],
      id: 560144,
      original_language: 'en',
      original_title: 'Skylines',
      overview:
        "When a virus threatens to turn the now earth-dwelling friendly alien hybrids against humans, Captain Rose Corley must lead a team of elite mercenaries on a mission to the alien world in order to save what's left of humanity.",
      popularity: 777.22,
      poster_path:
        'https://image.tmdb.org/t/p/w500/2W4ZvACURDyhiNnSIaFPHfNbny3.jpg',
      release_date: '2020-10-25',
      title: 'Skylines',
      video: false,
      vote_average: 5.7,
      vote_count: 173,
    },
    {
      adult: false,
      backdrop_path: '/yImmxRokQ48PD49ughXdpKTAsAU.jpg',
      genre_ids: [28, 12, 35, 10751],
      id: 644092,
      original_language: 'en',
      original_title: "Finding 'Ohana",
      overview:
        "Two Brooklyn siblings' summer in a rural Oahu town takes an exciting turn when a journal pointing to long-lost treasure sets them on an adventure, leading them to reconnect with their Hawaiian heritage.",
      popularity: 767.538,
      poster_path:
        'https://image.tmdb.org/t/p/w500/tTWl37oAYRXS3D5mEHmjveXXyrN.jpg',
      release_date: '2021-01-29',
      title: "Finding 'Ohana",
      video: false,
      vote_average: 6.7,
      vote_count: 129,
    },
    {
      adult: false,
      backdrop_path: '/9xeEGUZjgiKlI69jwIOi0hjKUIk.jpg',
      genre_ids: [14, 28, 12, 16],
      id: 664767,
      original_language: 'en',
      original_title: "Mortal Kombat Legends: Scorpion's Revenge",
      overview:
        'After the vicious slaughter of his family by stone-cold mercenary Sub-Zero, Hanzo Hasashi is exiled to the torturous Netherrealm. There, in exchange for his servitude to the sinister Quan Chi, he’s given a chance to avenge his family – and is resurrected as Scorpion, a lost soul bent on revenge. Back on Earthrealm, Lord Raiden gathers a team of elite warriors – Shaolin monk Liu Kang, Special Forces officer Sonya Blade and action star Johnny Cage – an unlikely band of heroes with one chance to save humanity. To do this, they must defeat Shang Tsung’s horde of Outworld gladiators and reign over the Mortal Kombat tournament.',
      popularity: 742.152,
      poster_path:
        'https://image.tmdb.org/t/p/w500/4VlXER3FImHeFuUjBShFamhIp9M.jpg',
      release_date: '2020-04-12',
      title: "Mortal Kombat Legends: Scorpion's Revenge",
      video: false,
      vote_average: 8.4,
      vote_count: 747,
    },
    {
      adult: false,
      backdrop_path: '/7TxeZVg2evMG42p0uSbMJpWNQ8A.jpg',
      genre_ids: [10751, 16, 14],
      id: 520946,
      original_language: 'en',
      original_title: '100% Wolf',
      overview:
        "Freddy Lupin, heir to a proud family line of werewolves, is in for a shock when on his 14th birthday his first 'warfing' goes awry, turning him into a ferocious poodle. The pack elders give Freddy until the next moonrise to prove he has the heart of a wolf, or risk being cast out forever. With the help of an unlikely ally in a streetwise stray named Batty, Freddy must prove he's 100% Wolf.",
      popularity: 650.326,
      poster_path:
        'https://image.tmdb.org/t/p/w500/2VrvxK4yxNCU6KVgo5TADJeBEQu.jpg',
      release_date: '2020-06-26',
      title: '100% Wolf',
      video: false,
      vote_average: 5.9,
      vote_count: 82,
    },
    {
      adult: false,
      backdrop_path: '/wzJRB4MKi3yK138bJyuL9nx47y6.jpg',
      genre_ids: [28, 53, 878],
      id: 577922,
      original_language: 'en',
      original_title: 'Tenet',
      overview:
        'Armed with only one word - Tenet - and fighting for the survival of the entire world, the Protagonist journeys through a twilight world of international espionage on a mission that will unfold in something beyond real time.',
      popularity: 618.795,
      poster_path:
        'https://image.tmdb.org/t/p/w500/k68nPLbIST6NP96JmTxmZijEvCA.jpg',
      release_date: '2020-08-22',
      title: 'Tenet',
      video: false,
      vote_average: 7.3,
      vote_count: 4435,
    },
    {
      adult: false,
      backdrop_path: '/9xNOiv6DZZjH7ABoUUDP0ZynouU.jpg',
      genre_ids: [28, 80],
      id: 495764,
      original_language: 'en',
      original_title:
        'Birds of Prey (and the Fantabulous Emancipation of One Harley Quinn)',
      overview:
        'Harley Quinn joins forces with a singer, an assassin and a police detective to help a young girl who had a hit placed on her after she stole a rare diamond from a crime lord.',
      popularity: 603.694,
      poster_path:
        'https://image.tmdb.org/t/p/w500/h4VB6m0RwcicVEZvzftYZyKXs6K.jpg',
      release_date: '2020-02-05',
      title:
        'Birds of Prey (and the Fantabulous Emancipation of One Harley Quinn)',
      video: false,
      vote_average: 7.1,
      vote_count: 6926,
    },
    {
      adult: false,
      backdrop_path: '/yR27bZPIkNhpGEIP3jKV2EifTgo.jpg',
      genre_ids: [16, 10751],
      id: 755812,
      original_language: 'fr',
      original_title: 'Miraculous World: New York, United HeroeZ',
      overview:
        'During a school field trip, Ladybug and Cat Noir meet the American superheroes, whom they have to save from an akumatised super-villain. They discover that Miraculous exist in the United States too.',
      popularity: 599.293,
      poster_path:
        'https://image.tmdb.org/t/p/w500/kIHgjAkuzvKBnmdstpBOo4AfZah.jpg',
      release_date: '2020-09-26',
      title: 'Miraculous World: New York, United HeroeZ',
      video: false,
      vote_average: 8.5,
      vote_count: 406,
    },
    {
      adult: false,
      backdrop_path: '/54yOImQgj8i85u9hxxnaIQBRUuo.jpg',
      genre_ids: [28, 80, 18, 53],
      id: 539885,
      original_language: 'en',
      original_title: 'Ava',
      overview:
        'A black ops assassin is forced to fight for her own survival after a job goes dangerously wrong.',
      popularity: 594.389,
      poster_path:
        'https://image.tmdb.org/t/p/w500/qzA87Wf4jo1h8JMk9GilyIYvwsA.jpg',
      release_date: '2020-07-02',
      title: 'Ava',
      video: false,
      vote_average: 5.6,
      vote_count: 1276,
    },
  ],
  total_pages: 500,
  total_results: 10000,
};

export const tvData = {
  page: 1,
  results: [
    {
      backdrop_path: '/lOr9NKxh4vMweufMOUDJjJhCRHW.jpg',
      first_air_date: '2021-01-15',
      genre_ids: [10765, 9648, 18],
      id: 85271,
      name: 'WandaVision',
      origin_country: ['US'],
      original_language: 'en',
      original_name: 'WandaVision',
      overview:
        'Wanda Maximoff and Vision—two super-powered beings living idealized suburban lives—begin to suspect that everything is not as it seems.',
      popularity: 3605.076,
      poster_path:
        'https://image.tmdb.org/t/p/w500/glKDfE6btIRcVB5zrjspRIs4r52.jpg',
      vote_average: 8.5,
      vote_count: 6313,
    },
    {
      backdrop_path: '/colNDt09PACkwtCgWILJQ8i6vSR.jpg',
      first_air_date: '2017-01-26',
      genre_ids: [9648, 18, 80],
      id: 69050,
      name: 'Riverdale',
      origin_country: ['US'],
      original_language: 'en',
      original_name: 'Riverdale',
      overview:
        'Set in the present, the series offers a bold, subversive take on Archie, Betty, Veronica and their friends, exploring the surreality of small-town life, the darkness and weirdness bubbling beneath Riverdale’s wholesome facade.',
      popularity: 1280.038,
      poster_path:
        'https://image.tmdb.org/t/p/w500/wRbjVBdDo5qHAEOVYoMWpM58FSA.jpg',
      vote_average: 8.6,
      vote_count: 10216,
    },
    {
      backdrop_path: '/uro2Khv7JxlzXtLb8tCIbRhkb9E.jpg',
      first_air_date: '2010-10-31',
      genre_ids: [10759, 18, 10765],
      id: 1402,
      name: 'The Walking Dead',
      origin_country: ['US'],
      original_language: 'en',
      original_name: 'The Walking Dead',
      overview:
        "Sheriff's deputy Rick Grimes awakens from a coma to find a post-apocalyptic world dominated by flesh-eating zombies. He sets out to find his family and encounters many other survivors along the way.",
      popularity: 1176.389,
      poster_path:
        'https://image.tmdb.org/t/p/w500/rqeYMLryjcawh2JeRpCVUDXYM5b.jpg',
      vote_average: 8,
      vote_count: 9835,
    },
    {
      backdrop_path: '/hvbGY8PItRa17A9QSpPCdZAD8Ge.jpg',
      first_air_date: '2021-02-19',
      genre_ids: [18, 9648],
      id: 97513,
      name: 'The Boarding School: Las Cumbres',
      origin_country: ['ES'],
      original_language: 'es',
      original_name: 'El Internado: Las Cumbres',
      overview:
        'In an inaccessible place between the mountains and isolated from the world, a school is located next to an old monastery. The students are rebellious and problematic young people who live under the strict and severe discipline imposed by the center to reintegrate them into society. The surrounding forest is home to ancient legends, threats that are still valid and that will immerse them in terrifying adventures.',
      popularity: 966.99,
      poster_path:
        'https://image.tmdb.org/t/p/w500/kl07N07l4XNjXF48oujzWXs40Dw.jpg',
      vote_average: 7.4,
      vote_count: 282,
    },
    {
      backdrop_path: '/ta5oblpMlEcIPIS2YGcq9XEkWK2.jpg',
      first_air_date: '2016-01-25',
      genre_ids: [80, 10765],
      id: 63174,
      name: 'Lucifer',
      origin_country: ['US'],
      original_language: 'en',
      original_name: 'Lucifer',
      overview:
        "Bored and unhappy as the Lord of Hell, Lucifer Morningstar abandoned his throne and retired to Los Angeles, where he has teamed up with LAPD detective Chloe Decker to take down criminals. But the longer he's away from the underworld, the greater the threat that the worst of humanity could escape.",
      popularity: 700.721,
      poster_path:
        'https://image.tmdb.org/t/p/w500/4EYPN5mVIhKLfxGruy7Dy41dTVn.jpg',
      vote_average: 8.5,
      vote_count: 7681,
    },
    {
      backdrop_path: '/mZjZgY6ObiKtVuKVDrnS9VnuNlE.jpg',
      first_air_date: '2017-09-25',
      genre_ids: [18],
      id: 71712,
      name: 'The Good Doctor',
      origin_country: ['US'],
      original_language: 'en',
      original_name: 'The Good Doctor',
      overview:
        "A young surgeon with Savant syndrome is recruited into the surgical unit of a prestigious hospital. The question will arise: can a person who doesn't have the ability to relate to people actually save their lives",
      popularity: 698.394,
      poster_path:
        'https://image.tmdb.org/t/p/w500/6tfT03sGp9k4c0J3dypjrI8TSAI.jpg',
      vote_average: 8.6,
      vote_count: 6942,
    },
    {
      backdrop_path: '/TXaR5xmz2ohHgnpf0YPWtZPlCO.jpg',
      first_air_date: '2021-02-23',
      genre_ids: [10759, 10765],
      id: 95057,
      name: 'Superman & Lois',
      origin_country: ['US'],
      original_language: 'en',
      original_name: 'Superman & Lois',
      overview:
        "After years of facing megalomaniacal supervillains, monsters wreaking havoc on Metropolis, and alien invaders intent on wiping out the human race, The Man of Steel aka Clark Kent and Lois Lane come face to face with one of their greatest challenges ever: dealing with all the stress, pressures and complexities that come with being working parents in today's society.",
      popularity: 691.641,
      poster_path:
        'https://image.tmdb.org/t/p/w500/6SJppowm7cdQgLkvoTlnTUSbjr9.jpg',
      vote_average: 8.6,
      vote_count: 222,
    },
    {
      backdrop_path: '/edmk8xjGBsYVIf4QtLY9WMaMcXZ.jpg',
      first_air_date: '2005-03-27',
      genre_ids: [18],
      id: 1416,
      name: "Grey's Anatomy",
      origin_country: ['US'],
      original_language: 'en',
      original_name: "Grey's Anatomy",
      overview:
        'Follows the personal and professional lives of a group of doctors at Seattle’s Grey Sloan Memorial Hospital.',
      popularity: 640.486,
      poster_path:
        'https://image.tmdb.org/t/p/w500/clnyhPqj1SNgpAdeSS6a6fwE6Bo.jpg',
      vote_average: 8.2,
      vote_count: 5391,
    },
    {
      backdrop_path: '/fRYwdeNjMqC30EhofPx5PlDpdun.jpg',
      first_air_date: '2018-10-25',
      genre_ids: [10765, 18],
      id: 79460,
      name: 'Legacies',
      origin_country: ['US'],
      original_language: 'en',
      original_name: 'Legacies',
      overview:
        'In a place where young witches, vampires, and werewolves are nurtured to be their best selves in spite of their worst impulses, Klaus Mikaelson’s daughter, 17-year-old Hope Mikaelson, Alaric Saltzman’s twins, Lizzie and Josie Saltzman, among others, come of age into heroes and villains at The Salvatore School for the Young and Gifted.',
      popularity: 611.916,
      poster_path:
        'https://image.tmdb.org/t/p/w500/qTZIgXrBKURBK1KrsT7fe3qwtl9.jpg',
      vote_average: 8.6,
      vote_count: 1640,
    },
    {
      backdrop_path: '/jC1KqsFx8ZyqJyQa2Ohi7xgL7XC.jpg',
      first_air_date: '2014-10-07',
      genre_ids: [18, 10765],
      id: 60735,
      name: 'The Flash',
      origin_country: ['US'],
      original_language: 'en',
      original_name: 'The Flash',
      overview:
        'After a particle accelerator causes a freak storm, CSI Investigator Barry Allen is struck by lightning and falls into a coma. Months later he awakens with the power of super speed, granting him the ability to move through Central City like an unseen guardian angel. Though initially excited by his newfound powers, Barry is shocked to discover he is not the only "meta-human" who was created in the wake of the accelerator explosion -- and not everyone is using their new powers for good. Barry partners with S.T.A.R. Labs and dedicates his life to protect the innocent. For now, only a few close friends and associates know that Barry is literally the fastest man alive, but it won\'t be long before the world learns what Barry Allen has become...The Flash.',
      popularity: 589.212,
      poster_path:
        'https://image.tmdb.org/t/p/w500/lJA2RCMfsWoskqlQhXPSLFQGXEJ.jpg',
      vote_average: 7.6,
      vote_count: 6796,
    },
    {
      backdrop_path: '/iqmJfU6DkqJra9PqIepaOJbzfa1.jpg',
      first_air_date: '2021-01-08',
      genre_ids: [99],
      id: 114695,
      name: 'Marvel Studios: Legends',
      origin_country: ['US'],
      original_language: 'en',
      original_name: 'Marvel Studios: Legends',
      overview:
        'Revisit the epic heroes, villains and moments from across the MCU in preparation for the stories still to come. Each dynamic segment feeds directly into the upcoming series — setting the stage for future events. This series weaves together the many threads that constitute the unparalleled Marvel Cinematic Universe.',
      popularity: 478.823,
      poster_path:
        'https://image.tmdb.org/t/p/w500/EpDuYIK81YtCUT3gH2JDpyj8Qk.jpg',
      vote_average: 7.6,
      vote_count: 302,
    },
    {
      backdrop_path: '/gL8myjGc2qrmqVosyGm5CWTir9A.jpg',
      first_air_date: '2018-05-02',
      genre_ids: [10759, 18],
      id: 77169,
      name: 'Cobra Kai',
      origin_country: ['US'],
      original_language: 'en',
      original_name: 'Cobra Kai',
      overview:
        'This Karate Kid sequel series picks up 30 years after the events of the 1984 All Valley Karate Tournament and finds Johnny Lawrence on the hunt for redemption by reopening the infamous Cobra Kai karate dojo. This reignites his old rivalry with the successful Daniel LaRusso, who has been working to maintain the balance in his life without mentor Mr. Miyagi.',
      popularity: 471.643,
      poster_path:
        'https://image.tmdb.org/t/p/w500/obLBdhLxheKg8Li1qO11r2SwmYO.jpg',
      vote_average: 8.1,
      vote_count: 2622,
    },
    {
      backdrop_path: '/aq2yEMgRQBPfRkrO0Repo2qhUAT.jpg',
      first_air_date: '2013-03-03',
      genre_ids: [10759, 18],
      id: 44217,
      name: 'Vikings',
      origin_country: ['CA'],
      original_language: 'en',
      original_name: 'Vikings',
      overview:
        "The adventures of Ragnar Lothbrok, the greatest hero of his age. The series tells the sagas of Ragnar's band of Viking brothers and his family, as he rises to become King of the Viking tribes. As well as being a fearless warrior, Ragnar embodies the Norse traditions of devotion to the gods. Legend has it that he was a direct descendant of Odin, the god of war and warriors.",
      popularity: 452.882,
      poster_path:
        'https://image.tmdb.org/t/p/w500/bQLrHIRNEkE3PdIWQrZHynQZazu.jpg',
      vote_average: 8,
      vote_count: 4119,
    },
    {
      backdrop_path: '/p7fwOnlxYYlB4A8U2b0JfX21Rr1.jpg',
      first_air_date: '2019-11-12',
      genre_ids: [10765, 10759, 37, 18],
      id: 82856,
      name: 'The Mandalorian',
      origin_country: ['US'],
      original_language: 'en',
      original_name: 'The Mandalorian',
      overview:
        'After the fall of the Galactic Empire, lawlessness has spread throughout the galaxy. A lone gunfighter makes his way through the outer reaches, earning his keep as a bounty hunter.',
      popularity: 429.916,
      poster_path:
        'https://image.tmdb.org/t/p/w500/sWgBv7LV2PRoQgkxwlibdGXKz1S.jpg',
      vote_average: 8.5,
      vote_count: 5917,
    },
    {
      backdrop_path: '/v2moumGovVAmDASYkjakIl2WrOM.jpg',
      first_air_date: '2016-09-23',
      genre_ids: [18, 10759],
      id: 67133,
      name: 'MacGyver',
      origin_country: ['US'],
      original_language: 'en',
      original_name: 'MacGyver',
      overview:
        '20-something Angus MacGyver creates a clandestine organization where he uses his knack for solving problems in unconventional ways to help prevent disasters from happening.',
      popularity: 417.579,
      poster_path:
        'https://image.tmdb.org/t/p/w500/2zAogx9dmSAu2HYxbWzHe4ZaNY5.jpg',
      vote_average: 7.1,
      vote_count: 554,
    },
    {
      backdrop_path: '/suopoADq0k8YZr4dQXcU6pToj6s.jpg',
      first_air_date: '2011-04-17',
      genre_ids: [10765, 18, 10759],
      id: 1399,
      name: 'Game of Thrones',
      origin_country: ['US'],
      original_language: 'en',
      original_name: 'Game of Thrones',
      overview:
        "Seven noble families fight for control of the mythical land of Westeros. Friction between the houses leads to full-scale war. All while a very ancient evil awakens in the farthest north. Amidst the war, a neglected military order of misfits, the Night's Watch, is all that stands between the realms of men and icy horrors beyond.",
      popularity: 389.393,
      poster_path:
        'https://image.tmdb.org/t/p/w500/u3bZgnGQ9T01sWNhyveQz0wH0Hl.jpg',
      vote_average: 8.4,
      vote_count: 13213,
    },
    {
      backdrop_path: '/k7T9xRyzP41wBVNyNeLmh8Ch7gD.jpg',
      first_air_date: '2009-09-10',
      genre_ids: [18, 10765],
      id: 18165,
      name: 'The Vampire Diaries',
      origin_country: ['US'],
      original_language: 'en',
      original_name: 'The Vampire Diaries',
      overview:
        'The story of two vampire brothers obsessed with the same girl, who bears a striking resemblance to the beautiful but ruthless vampire they knew and loved in 1864.',
      popularity: 368.81,
      poster_path:
        'https://image.tmdb.org/t/p/w500/aBkVgChtyyJaHyZh1gfd8DbzQon.jpg',
      vote_average: 8.3,
      vote_count: 5291,
    },
    {
      backdrop_path: '/hBYvHCcZX4dyvXeM0NTBh5uJIk3.jpg',
      first_air_date: '2019-01-08',
      genre_ids: [18],
      id: 80006,
      name: 'Good Trouble',
      origin_country: ['US'],
      original_language: 'en',
      original_name: 'Good Trouble',
      overview:
        'After moving to The Coterie in Downtown Los Angeles, Callie and Mariana Foster realize that living on their own is not all that it’s cracked up to be.',
      popularity: 367.656,
      poster_path:
        'https://image.tmdb.org/t/p/w500/b9OwPQZr4dVv7K8SrUbAYJ35uLg.jpg',
      vote_average: 8,
      vote_count: 87,
    },
    {
      backdrop_path: '/uY3MJohUpY7UMMTK90BIhX5txEs.jpg',
      first_air_date: '2017-04-30',
      genre_ids: [18, 9648, 10765],
      id: 46639,
      name: 'American Gods',
      origin_country: ['US'],
      original_language: 'en',
      original_name: 'American Gods',
      overview:
        "An ex-con becomes the traveling partner of a conman who turns out to be one of the older gods trying to recruit troops to battle the upstart deities. Based on Neil Gaiman's fantasy novel.",
      popularity: 338.737,
      poster_path:
        'https://image.tmdb.org/t/p/w500/3KCAZaKHmoMIN9dHutqaMtubQqD.jpg',
      vote_average: 7.1,
      vote_count: 952,
    },
    {
      backdrop_path: '/oAkpvVvoyZWMo9cpNk3aQoVKsjM.jpg',
      first_air_date: '2016-07-19',
      genre_ids: [10759, 80, 18, 9648],
      id: 67335,
      name: 'Sin senos sí hay paraíso',
      origin_country: ['CO'],
      original_language: 'es',
      original_name: 'Sin senos sí hay paraíso',
      overview:
        'A young woman born in a mafia-controlled town seeks revenge on those who wrongfully harmed and imprisoned her family.',
      popularity: 338.176,
      poster_path:
        'https://image.tmdb.org/t/p/w500/ulcGG2JKjbVMQFIux1vcQGN1pQi.jpg',
      vote_average: 7.5,
      vote_count: 1897,
    },
  ],
  total_pages: 500,
  total_results: 10000,
};

export const peopleData = {
  page: 1,
  results: [
    {
      adult: false,
      gender: 1,
      id: 1245,
      known_for: [
        {
          adult: false,
          backdrop_path: '/kwUQFeFXOOpgloMgZaadhzkbTI4.jpg',
          genre_ids: [878, 28, 12],
          id: 24428,
          media_type: 'movie',
          original_language: 'en',
          original_title: 'The Avengers',
          overview:
            'When an unexpected enemy emerges and threatens global safety and security, Nick Fury, director of the international peacekeeping agency known as S.H.I.E.L.D., finds himself in need of a team to pull the world back from the brink of disaster. Spanning the globe, a daring recruitment effort begins!',
          poster_path: '/RYMX2wcKCBAr24UyPD7xwmjaTn.jpg',
          release_date: '2012-04-25',
          title: 'The Avengers',
          video: false,
          vote_average: 7.7,
          vote_count: 24146,
        },
        {
          adult: false,
          backdrop_path: '/lmZFxXgJE3vgrciwuDib0N8CfQo.jpg',
          genre_ids: [12, 28, 878],
          id: 299536,
          media_type: 'movie',
          original_language: 'en',
          original_title: 'Avengers: Infinity War',
          overview:
            'As the Avengers and their allies have continued to protect the world from threats too large for any one hero to handle, a new danger has emerged from the cosmic shadows: Thanos. A despot of intergalactic infamy, his goal is to collect all six Infinity Stones, artifacts of unimaginable power, and use them to inflict his twisted will on all of reality. Everything the Avengers have fought for has led up to this moment - the fate of Earth and existence itself has never been more uncertain.',
          poster_path: '/7WsyChQLEftFiDOVTGkv3hFpyyt.jpg',
          release_date: '2018-04-25',
          title: 'Avengers: Infinity War',
          video: false,
          vote_average: 8.3,
          vote_count: 21117,
        },
        {
          adult: false,
          backdrop_path: '/yfpA0hb18w9TR2XBm1P9zhkBsQ9.jpg',
          genre_ids: [12, 28, 878],
          id: 271110,
          media_type: 'movie',
          original_language: 'en',
          original_title: 'Captain America: Civil War',
          overview:
            'Following the events of Age of Ultron, the collective governments of the world pass an act designed to regulate all superhuman activity. This polarizes opinion amongst the Avengers, causing two factions to side with Iron Man or Captain America, which causes an epic battle between former allies.',
          poster_path: '/rAGiXaUfPzY7CDEyNKUofk3Kw2e.jpg',
          release_date: '2016-04-27',
          title: 'Captain America: Civil War',
          video: false,
          vote_average: 7.4,
          vote_count: 17589,
        },
      ],
      known_for_department: 'Acting',
      name: 'Scarlett Johansson',
      popularity: 45.208,
      profile_path:
        'https://image.tmdb.org/t/p/h632/6NsMbJXRlDZuDzatN2akFdGuTvx.jpg',
    },
    {
      adult: false,
      gender: 2,
      id: 976,
      known_for: [
        {
          adult: false,
          backdrop_path: '/mRfI3y2oAd7ejur2di09xC9niqp.jpg',
          genre_ids: [28, 53, 80],
          id: 82992,
          media_type: 'movie',
          original_language: 'en',
          original_title: 'Fast & Furious 6',
          overview:
            'Hobbs has Dominic and Brian reassemble their crew to take down a team of mercenaries: Dominic unexpectedly gets convoluted also facing his presumed deceased girlfriend, Letty.',
          poster_path: '/n31VRDodbaZxkrZmmzyYSFNVpW5.jpg',
          release_date: '2013-05-21',
          title: 'Fast & Furious 6',
          video: false,
          vote_average: 6.8,
          vote_count: 8473,
        },
        {
          adult: false,
          backdrop_path: '/vkQvqH8WQkUiNklDcbUtHEUgSNQ.jpg',
          genre_ids: [28, 53],
          id: 168259,
          media_type: 'movie',
          original_language: 'en',
          original_title: 'Furious 7',
          overview:
            'Deckard Shaw seeks revenge against Dominic Toretto and his family for his comatose brother.',
          poster_path: '/ktofZ9Htrjiy0P6LEowsDaxd3Ri.jpg',
          release_date: '2015-04-01',
          title: 'Furious 7',
          video: false,
          vote_average: 7.3,
          vote_count: 8149,
        },
        {
          adult: false,
          backdrop_path: '/jzdnhRhG0dsuYorwvSqPqqnM1cV.jpg',
          genre_ids: [28, 80, 53],
          id: 337339,
          media_type: 'movie',
          original_language: 'en',
          original_title: 'The Fate of the Furious',
          overview:
            'When a mysterious woman seduces Dom into the world of crime and a betrayal of those closest to him, the crew face trials that will test them as never before.',
          poster_path: '/dImWM7GJqryWJO9LHa3XQ8DD5NH.jpg',
          release_date: '2017-04-12',
          title: 'The Fate of the Furious',
          video: false,
          vote_average: 6.9,
          vote_count: 8036,
        },
      ],
      known_for_department: 'Acting',
      name: 'Jason Statham',
      popularity: 35.881,
      profile_path:
        'https://image.tmdb.org/t/p/h632/lldeQ91GwIVff43JBrpdbAAeYWj.jpg',
    },
    {
      adult: false,
      gender: 2,
      id: 62,
      known_for: [
        {
          adult: false,
          backdrop_path: '/w7RDIgQM6bLT7JXtH4iUQd3Iwxm.jpg',
          genre_ids: [53, 80],
          id: 680,
          media_type: 'movie',
          original_language: 'en',
          original_title: 'Pulp Fiction',
          overview:
            "A burger-loving hit man, his philosophical partner, a drug-addled gangster's moll and a washed-up boxer converge in this sprawling, comedic crime caper. Their adventures unfurl in three stories that ingeniously trip back and forth in time.",
          poster_path: '/plnlrtBUULT0rh3Xsjmpubiso3L.jpg',
          release_date: '1994-09-10',
          title: 'Pulp Fiction',
          video: false,
          vote_average: 8.5,
          vote_count: 20668,
        },
        {
          adult: false,
          backdrop_path: '/9pkZesKMnblFfKxEhQx45YQ2kIe.jpg',
          genre_ids: [27, 53],
          id: 381288,
          media_type: 'movie',
          original_language: 'en',
          original_title: 'Split',
          overview:
            'Though Kevin has evidenced 23 personalities to his trusted psychiatrist, Dr. Fletcher, there remains one still submerged who is set to materialize and dominate all the others. Compelled to abduct three teenage girls led by the willful, observant Casey, Kevin reaches a war for survival among all of those contained within him — as well as everyone around him — as the walls between his compartments shatter apart.',
          poster_path: '/bqb9WsmZmDIKxqYmBJ9lj7J6hzn.jpg',
          release_date: '2017-01-09',
          title: 'Split',
          video: false,
          vote_average: 7.3,
          vote_count: 13524,
        },
        {
          adult: false,
          backdrop_path: '/6TjllWT3cGrPFyqDXurVZ3L8bBi.jpg',
          genre_ids: [9648, 53, 18],
          id: 745,
          media_type: 'movie',
          original_language: 'en',
          original_title: 'The Sixth Sense',
          overview:
            'An eight year old boy named Cole Sear, who believes he can see dead people, aids the help of a child psychologist named Malcolm Crowe.',
          poster_path: '/fIssD3w3SvIhPPmVo4WMgZDVLID.jpg',
          release_date: '1999-08-06',
          title: 'The Sixth Sense',
          video: false,
          vote_average: 7.9,
          vote_count: 8347,
        },
      ],
      known_for_department: 'Acting',
      name: 'Bruce Willis',
      popularity: 32.805,
      profile_path:
        'https://image.tmdb.org/t/p/h632/jLnMgbZ6FnBsZBPkFzvEXk9A1SW.jpg',
    },
    {
      adult: false,
      gender: 1,
      id: 56734,
      known_for: [
        {
          adult: false,
          backdrop_path: '/P4bGyJQF0shAcRku3I2perNUQR.jpg',
          genre_ids: [28, 80],
          id: 23483,
          media_type: 'movie',
          original_language: 'en',
          original_title: 'Kick-Ass',
          overview:
            'Dave Lizewski is an unnoticed high school student and comic book fan who one day decides to become a super-hero, even though he has no powers, training or meaningful reason to do so.',
          poster_path: '/GPiMXaDC2NdDIldLgtijHFTeKH.jpg',
          release_date: '2010-03-22',
          title: 'Kick-Ass',
          video: false,
          vote_average: 7.1,
          vote_count: 9199,
        },
        {
          adult: false,
          backdrop_path: '/x0emyxKfPMfxuW71xrzV07cmg1e.jpg',
          genre_ids: [35, 18, 10749],
          id: 19913,
          media_type: 'movie',
          original_language: 'en',
          original_title: '(500) Days of Summer',
          overview:
            'Tom, greeting-card writer and hopeless romantic, is caught completely off-guard when his girlfriend, Summer, suddenly dumps him. He reflects on their 500 days together to try to figure out where their love affair went sour, and in doing so, Tom rediscovers his true passions in life.',
          poster_path: '/f9mbM0YMLpYemcWx6o2WeiYQLDP.jpg',
          release_date: '2009-07-17',
          title: '(500) Days of Summer',
          video: false,
          vote_average: 7.2,
          vote_count: 7387,
        },
        {
          adult: false,
          backdrop_path: '/9vAoubhoZE8aSkUZoSfxs3UWZhO.jpg',
          genre_ids: [53, 28, 80],
          id: 156022,
          media_type: 'movie',
          original_language: 'en',
          original_title: 'The Equalizer',
          overview:
            'McCall believes he has put his mysterious past behind him and dedicated himself to beginning a new, quiet life. But when he meets Teri, a young girl under the control of ultra-violent Russian gangsters, he can’t stand idly by – he has to help her. Armed with hidden skills that allow him to serve vengeance against anyone who would brutalize the helpless, McCall comes out of his self-imposed retirement and finds his desire for justice reawakened. If someone has a problem, if the odds are stacked against them, if they have nowhere else to turn, McCall will help. He is The Equalizer.',
          poster_path: '/9u4yW7yPA0BQ2pv9XwiNzItwvp8.jpg',
          release_date: '2014-09-24',
          title: 'The Equalizer',
          video: false,
          vote_average: 7.2,
          vote_count: 6427,
        },
      ],
      known_for_department: 'Acting',
      name: 'Chloë Grace Moretz',
      popularity: 31.854,
      profile_path:
        'https://image.tmdb.org/t/p/h632/uIlu8tHJahd605Tknh9XbTbuptR.jpg',
    },
    {
      adult: false,
      gender: 1,
      id: 63,
      known_for: [
        {
          adult: false,
          backdrop_path: '/wgvc3PmjQGtYYDWaeuV867mnFDs.jpg',
          genre_ids: [12, 14, 28, 53, 878],
          id: 18,
          media_type: 'movie',
          original_language: 'en',
          original_title: 'The Fifth Element',
          overview:
            'In 2257, a taxi driver is unintentionally given the task of saving a young girl who is part of the key that will ensure the survival of humanity.',
          poster_path: '/fPtlCO1yQtnoLHOwKtWz7db6RGU.jpg',
          release_date: '1997-05-02',
          title: 'The Fifth Element',
          video: false,
          vote_average: 7.5,
          vote_count: 8002,
        },
        {
          adult: false,
          backdrop_path: '/4Ni6XbdQV4xpR9IrT94BXH8PCcw.jpg',
          genre_ids: [27, 28, 878],
          id: 1576,
          media_type: 'movie',
          original_language: 'en',
          original_title: 'Resident Evil',
          overview:
            'When a virus leaks from a top-secret facility, turning all resident researchers into ravenous zombies and their lab animals into mutated hounds from hell, the government sends in an elite military task force to contain the outbreak. Alice and Rain are charged with leading the mission. But they only have three hours before the pathogen becomes airborne and infects the world.',
          poster_path: '/1UKNef590A0ZaMnxsscIcWuK1Em.jpg',
          release_date: '2002-03-15',
          title: 'Resident Evil',
          video: false,
          vote_average: 6.6,
          vote_count: 4516,
        },
        {
          adult: false,
          backdrop_path: '/oMqAclK9lSn48GbpWo3mFxCy8XR.jpg',
          genre_ids: [35],
          id: 9398,
          media_type: 'movie',
          original_language: 'en',
          original_title: 'Zoolander',
          overview:
            "Clear the runway for Derek Zoolander, VH1's three-time male model of the year. His face falls when hippie-chic Hansel scooters in to steal this year's award. The evil fashion guru Mugatu seizes the opportunity to turn Derek into a killing machine. It's a well-designed conspiracy and only with the help of Hansel and a few well-chosen accessories like Matilda can Derek make the world safe for male models everywhere.",
          poster_path: '/3ihaCjYmQ1vIh6PNvlZ2rdBRSak.jpg',
          release_date: '2001-09-28',
          title: 'Zoolander',
          video: false,
          vote_average: 6.2,
          vote_count: 3136,
        },
      ],
      known_for_department: 'Acting',
      name: 'Milla Jovovich',
      popularity: 31.722,
      profile_path:
        'https://image.tmdb.org/t/p/h632/usWnHCzbADijULREZYSJ0qfM00y.jpg',
    },
    {
      adult: false,
      gender: 2,
      id: 18897,
      known_for: [
        {
          adult: false,
          backdrop_path: '/qdthf9WrRDSaIkGVQGhhJ9pz1hn.jpg',
          genre_ids: [28, 12, 16, 10751, 35],
          id: 9502,
          media_type: 'movie',
          original_language: 'en',
          original_title: 'Kung Fu Panda',
          overview:
            'When the Valley of Peace is threatened, lazy Po the panda discovers his destiny as the "chosen one" and trains to become a kung fu hero, but transforming the unsleek slacker into a brave warrior won\'t be easy. It\'s up to Master Shifu and the Furious Five -- Tigress, Crane, Mantis, Viper and Monkey -- to give it a try.',
          poster_path: '/wWt4JYXTg5Wr3xBW2phBrMKgp3x.jpg',
          release_date: '2008-06-04',
          title: 'Kung Fu Panda',
          video: false,
          vote_average: 7.1,
          vote_count: 8207,
        },
        {
          adult: false,
          backdrop_path: '/iKJNE3QV0wEc9VMFuHYSZVhmSN9.jpg',
          genre_ids: [16, 10751],
          id: 49444,
          media_type: 'movie',
          original_language: 'en',
          original_title: 'Kung Fu Panda 2',
          overview:
            'Po is now living his dream as The Dragon Warrior, protecting the Valley of Peace alongside his friends and fellow kung fu masters, The Furious Five - Tigress, Crane, Mantis, Viper and Monkey. But Po’s new life of awesomeness is threatened by the emergence of a formidable villain, who plans to use a secret, unstoppable weapon to conquer China and destroy kung fu. It is up to Po and The Furious Five to journey across China to face this threat and vanquish it. But how can Po stop a weapon that can stop kung fu? He must look to his past and uncover the secrets of his mysterious origins; only then will he be able to unlock the strength he needs to succeed.',
          poster_path: '/mtqqD00vB4PGRt20gWtGqFhrkd0.jpg',
          release_date: '2011-05-25',
          title: 'Kung Fu Panda 2',
          video: false,
          vote_average: 6.8,
          vote_count: 4862,
        },
        {
          adult: false,
          backdrop_path: '/y2Cl2LBYaabgtSLlOa4VqnOiNin.jpg',
          genre_ids: [28, 12, 18, 10751],
          id: 38575,
          media_type: 'movie',
          original_language: 'en',
          original_title: 'The Karate Kid',
          overview:
            "Twelve-year-old Dre Parker could have been the most popular kid in Detroit, but his mother's latest career move has landed him in China. Dre immediately falls for his classmate Mei Ying but the cultural differences make such a friendship impossible. Even worse, Dre's feelings make him an enemy of the class bully, Cheng. With no friends in a strange land, Dre has nowhere to turn but maintenance man Mr. Han, who is a kung fu master. As Han teaches Dre that kung fu is not about punches and parries, but maturity and calm, Dre realizes that facing down the bullies will be the fight of his life.",
          poster_path: '/tAMQREOoztvluqrfHiGHFVfB04B.jpg',
          release_date: '2010-06-10',
          title: 'The Karate Kid',
          video: false,
          vote_average: 6.5,
          vote_count: 4303,
        },
      ],
      known_for_department: 'Acting',
      name: 'Jackie Chan',
      popularity: 30.174,
      profile_path:
        'https://image.tmdb.org/t/p/h632/nraZoTzwJQPHspAVsKfgl3RXKKa.jpg',
    },
    {
      adult: false,
      gender: 1,
      id: 550843,
      known_for: [
        {
          adult: false,
          backdrop_path: '/lmZFxXgJE3vgrciwuDib0N8CfQo.jpg',
          genre_ids: [12, 28, 878],
          id: 299536,
          media_type: 'movie',
          original_language: 'en',
          original_title: 'Avengers: Infinity War',
          overview:
            'As the Avengers and their allies have continued to protect the world from threats too large for any one hero to handle, a new danger has emerged from the cosmic shadows: Thanos. A despot of intergalactic infamy, his goal is to collect all six Infinity Stones, artifacts of unimaginable power, and use them to inflict his twisted will on all of reality. Everything the Avengers have fought for has led up to this moment - the fate of Earth and existence itself has never been more uncertain.',
          poster_path: '/7WsyChQLEftFiDOVTGkv3hFpyyt.jpg',
          release_date: '2018-04-25',
          title: 'Avengers: Infinity War',
          video: false,
          vote_average: 8.3,
          vote_count: 21117,
        },
        {
          adult: false,
          backdrop_path: '/yfpA0hb18w9TR2XBm1P9zhkBsQ9.jpg',
          genre_ids: [12, 28, 878],
          id: 271110,
          media_type: 'movie',
          original_language: 'en',
          original_title: 'Captain America: Civil War',
          overview:
            'Following the events of Age of Ultron, the collective governments of the world pass an act designed to regulate all superhuman activity. This polarizes opinion amongst the Avengers, causing two factions to side with Iron Man or Captain America, which causes an epic battle between former allies.',
          poster_path: '/rAGiXaUfPzY7CDEyNKUofk3Kw2e.jpg',
          release_date: '2016-04-27',
          title: 'Captain America: Civil War',
          video: false,
          vote_average: 7.4,
          vote_count: 17589,
        },
        {
          adult: false,
          backdrop_path: '/8i6ZDk97Vyh0jHohMG4vFeFuKJh.jpg',
          genre_ids: [28, 12, 878],
          id: 99861,
          media_type: 'movie',
          original_language: 'en',
          original_title: 'Avengers: Age of Ultron',
          overview:
            'When Tony Stark tries to jumpstart a dormant peacekeeping program, things go awry and Earth’s Mightiest Heroes are put to the ultimate test as the fate of the planet hangs in the balance. As the villainous Ultron emerges, it is up to The Avengers to stop him from enacting his terrible plans, and soon uneasy alliances and unexpected action pave the way for an epic and unique global adventure.',
          poster_path: '/4ssDuvEDkSArWEdyBl2X5EHvYKU.jpg',
          release_date: '2015-04-22',
          title: 'Avengers: Age of Ultron',
          video: false,
          vote_average: 7.3,
          vote_count: 17422,
        },
      ],
      known_for_department: 'Acting',
      name: 'Elizabeth Olsen',
      popularity: 28.592,
      profile_path:
        'https://image.tmdb.org/t/p/h632/wIU675y4dofIDVuhaNWPizJNtep.jpg',
    },
    {
      adult: false,
      gender: 2,
      id: 31,
      known_for: [
        {
          adult: false,
          backdrop_path: '/tlEFuIlaxRPXIYVHXbOSAMCfWqk.jpg',
          genre_ids: [35, 18, 10749],
          id: 13,
          media_type: 'movie',
          original_language: 'en',
          original_title: 'Forrest Gump',
          overview:
            'A man with a low IQ has accomplished great things in his life and been present during significant historic events—in each case, far exceeding what anyone imagined he could do. But despite all he has achieved, his one true love eludes him.',
          poster_path: '/h5J4W4veyxMXDMjeNxZI46TsHOb.jpg',
          release_date: '1994-07-06',
          title: 'Forrest Gump',
          video: false,
          vote_average: 8.5,
          vote_count: 20057,
        },
        {
          adult: false,
          backdrop_path: '/3Rfvhy1Nl6sSGJwyjb0QiZzZYlB.jpg',
          genre_ids: [16, 12, 10751, 35],
          id: 862,
          media_type: 'movie',
          original_language: 'en',
          original_title: 'Toy Story',
          overview:
            "Led by Woody, Andy's toys live happily in his room until Andy's birthday brings Buzz Lightyear onto the scene. Afraid of losing his place in Andy's heart, Woody plots against Buzz. But when circumstances separate Buzz and Woody from their owner, the duo eventually learns to put aside their differences.",
          poster_path: '/uXDfjJbdP4ijW5hWSBrPrlKpxab.jpg',
          release_date: '1995-10-30',
          title: 'Toy Story',
          video: false,
          vote_average: 7.9,
          vote_count: 13645,
        },
        {
          adult: false,
          backdrop_path: '/xMIyotorUv2Yz7zpQz2QYc8wkWB.jpg',
          genre_ids: [14, 18, 80],
          id: 497,
          media_type: 'movie',
          original_language: 'en',
          original_title: 'The Green Mile',
          overview:
            "A supernatural tale set on death row in a Southern prison, where gentle giant John Coffey possesses the mysterious power to heal people's ailments. When the cell block's head guard, Paul Edgecomb, recognizes Coffey's miraculous gift, he tries desperately to help stave off the condemned man's execution.",
          poster_path: '/velWPhVMQeQKcxggNEU8YmIo52R.jpg',
          release_date: '1999-12-10',
          title: 'The Green Mile',
          video: false,
          vote_average: 8.5,
          vote_count: 11868,
        },
      ],
      known_for_department: 'Acting',
      name: 'Tom Hanks',
      popularity: 26.374,
      profile_path:
        'https://image.tmdb.org/t/p/h632/zVyoR2ZNiVGymjZK4MMJHIdpxoW.jpg',
    },
    {
      adult: false,
      gender: 2,
      id: 18918,
      known_for: [
        {
          adult: false,
          backdrop_path: '/zJDMuXQDraHjtF53wikmyBQIcYe.jpg',
          genre_ids: [28, 12, 35, 14],
          id: 353486,
          media_type: 'movie',
          original_language: 'en',
          original_title: 'Jumanji: Welcome to the Jungle',
          overview:
            "The tables are turned as four teenagers are sucked into Jumanji's world - pitted against rhinos, black mambas and an endless variety of jungle traps and puzzles. To survive, they'll play as characters from the game.",
          poster_path: '/pSgXKPU5h6U89ipF7HBYajvYt7j.jpg',
          release_date: '2017-12-09',
          title: 'Jumanji: Welcome to the Jungle',
          video: false,
          vote_average: 6.8,
          vote_count: 10378,
        },
        {
          adult: false,
          backdrop_path: '/oWU6dgu3RgdSZElkhbZuoPtkWAJ.jpg',
          genre_ids: [12, 35, 10751, 16],
          id: 277834,
          media_type: 'movie',
          original_language: 'en',
          original_title: 'Moana',
          overview:
            "In Ancient Polynesia, when a terrible curse incurred by Maui reaches an impetuous Chieftain's daughter's island, she answers the Ocean's call to seek out the demigod to set things right.",
          poster_path: '/vNJFiwtsl7Twww7C0uM4qPnygNw.jpg',
          release_date: '2016-11-23',
          title: 'Moana',
          video: false,
          vote_average: 7.6,
          vote_count: 9243,
        },
        {
          adult: false,
          backdrop_path: '/mRfI3y2oAd7ejur2di09xC9niqp.jpg',
          genre_ids: [28, 53, 80],
          id: 82992,
          media_type: 'movie',
          original_language: 'en',
          original_title: 'Fast & Furious 6',
          overview:
            'Hobbs has Dominic and Brian reassemble their crew to take down a team of mercenaries: Dominic unexpectedly gets convoluted also facing his presumed deceased girlfriend, Letty.',
          poster_path: '/n31VRDodbaZxkrZmmzyYSFNVpW5.jpg',
          release_date: '2013-05-21',
          title: 'Fast & Furious 6',
          video: false,
          vote_average: 6.8,
          vote_count: 8481,
        },
      ],
      known_for_department: 'Acting',
      name: 'Dwayne Johnson',
      popularity: 26.072,
      profile_path:
        'https://image.tmdb.org/t/p/h632/cgoy7t5Ve075naBPcewZrc08qGw.jpg',
    },
    {
      adult: false,
      gender: 2,
      id: 48,
      known_for: [
        {
          adult: false,
          backdrop_path: '/vRQnzOn4HjIMX4LBq9nHhFXbsSu.jpg',
          genre_ids: [12, 14, 28],
          id: 120,
          media_type: 'movie',
          original_language: 'en',
          original_title: 'The Lord of the Rings: The Fellowship of the Ring',
          overview:
            'Young hobbit Frodo Baggins, after inheriting a mysterious ring from his uncle Bilbo, must leave his home in order to keep it from falling into the hands of its evil creator. Along the way, a fellowship is formed to protect the ringbearer and make sure that the ring arrives at its final destination: Mt. Doom, the only place where it can be destroyed.',
          poster_path: '/6oom5QYQ2yQTMJIbnvbkBL9cHo6.jpg',
          release_date: '2001-12-18',
          title: 'The Lord of the Rings: The Fellowship of the Ring',
          video: false,
          vote_average: 8.3,
          vote_count: 18697,
        },
        {
          adult: false,
          backdrop_path: '/lXhgCODAbBXL5buk9yEmTpOoOgR.jpg',
          genre_ids: [12, 14, 28],
          id: 122,
          media_type: 'movie',
          original_language: 'en',
          original_title: 'The Lord of the Rings: The Return of the King',
          overview:
            "Aragorn is revealed as the heir to the ancient kings as he, Gandalf and the other members of the broken fellowship struggle to save Gondor from Sauron's forces. Meanwhile, Frodo and Sam take the ring closer to the heart of Mordor, the dark lord's realm.",
          poster_path: '/rCzpDGLbOoPwLjy3OAm5NUPOTrC.jpg',
          release_date: '2003-12-01',
          title: 'The Lord of the Rings: The Return of the King',
          video: false,
          vote_average: 8.5,
          vote_count: 17233,
        },
        {
          adult: false,
          backdrop_path: '/7tNTPZMb13W0AhkcuoL6myRrNRr.jpg',
          genre_ids: [12, 14, 28],
          id: 121,
          media_type: 'movie',
          original_language: 'en',
          original_title: 'The Lord of the Rings: The Two Towers',
          overview:
            'Frodo and Sam are trekking to Mordor to destroy the One Ring of Power while Gimli, Legolas and Aragorn search for the orc-captured Merry and Pippin. All along, nefarious wizard Saruman awaits the Fellowship members at the Orthanc Tower in Isengard.',
          poster_path: '/5VTN0pR8gcqV3EPUHHfMGnJYN9L.jpg',
          release_date: '2002-12-18',
          title: 'The Lord of the Rings: The Two Towers',
          video: false,
          vote_average: 8.3,
          vote_count: 16133,
        },
      ],
      known_for_department: 'Acting',
      name: 'Sean Bean',
      popularity: 25.634,
      profile_path:
        'https://image.tmdb.org/t/p/h632/kTjiABk3TJ3yI0Cto5RsvyT6V3o.jpg',
    },
    {
      adult: false,
      gender: 2,
      id: 68610,
      known_for: [
        {
          adult: false,
          backdrop_path: '/x0emyxKfPMfxuW71xrzV07cmg1e.jpg',
          genre_ids: [35, 18, 10749],
          id: 19913,
          media_type: 'movie',
          original_language: 'en',
          original_title: '(500) Days of Summer',
          overview:
            'Tom, greeting-card writer and hopeless romantic, is caught completely off-guard when his girlfriend, Summer, suddenly dumps him. He reflects on their 500 days together to try to figure out where their love affair went sour, and in doing so, Tom rediscovers his true passions in life.',
          poster_path: '/f9mbM0YMLpYemcWx6o2WeiYQLDP.jpg',
          release_date: '2009-07-17',
          title: '(500) Days of Summer',
          video: false,
          vote_average: 7.2,
          vote_count: 7366,
        },
        {
          backdrop_path: '/5s9XHTB9SLPdg3mNU6BlSLnZ9Qq.jpg',
          first_air_date: '2011-01-09',
          genre_ids: [18, 35],
          id: 34307,
          media_type: 'tv',
          name: 'Shameless',
          origin_country: ['US'],
          original_language: 'en',
          original_name: 'Shameless',
          overview:
            "Chicagoan Frank Gallagher is the proud single dad of six smart, industrious, independent kids, who without him would be... perhaps better off. When Frank's not at the bar spending what little money they have, he's passed out on the floor. But the kids have found ways to grow up in spite of him. They may not be like any family you know, but they make no apologies for being exactly who they are.",
          poster_path: '/9akij7PqZ1g6zl42DQQTtL9CTSb.jpg',
          vote_average: 7.9,
          vote_count: 1177,
        },
        {
          adult: false,
          backdrop_path: '/eROomCPyRykUErrRGCkdncLZ3gK.jpg',
          genre_ids: [35],
          id: 11211,
          media_type: 'movie',
          original_language: 'en',
          original_title: 'Bring It On: All or Nothing',
          overview:
            'A transfer student at a rough high school tries joining the cheer-leading squad and finds that she not only has to face off against the head cheerleader, but also against her former school in preparation for a cheer-off competition.',
          poster_path: '/5jdoQsOfSIILTfFGBOww2o3zjgV.jpg',
          release_date: '2006-08-08',
          title: 'Bring It On: All or Nothing',
          video: false,
          vote_average: 6.5,
          vote_count: 550,
        },
      ],
      known_for_department: 'Acting',
      name: 'Gus Carr',
      popularity: 25.076,
      profile_path:
        'https://image.tmdb.org/t/p/h632/5UpXtBwY0TzvQlxToHPwN206sRR.jpg',
    },
    {
      adult: false,
      gender: 1,
      id: 90633,
      known_for: [
        {
          adult: false,
          backdrop_path: '/6iUNJZymJBMXXriQyFZfLAKnjO6.jpg',
          genre_ids: [28, 12, 14],
          id: 297762,
          media_type: 'movie',
          original_language: 'en',
          original_title: 'Wonder Woman',
          overview:
            'An Amazon princess comes to the world of Man in the grips of the First World War to confront the forces of evil and bring an end to human conflict.',
          poster_path: '/gfJGlDaHuWimErCr5Ql0I8x9QSy.jpg',
          release_date: '2017-05-30',
          title: 'Wonder Woman',
          video: false,
          vote_average: 7.3,
          vote_count: 16049,
        },
        {
          adult: false,
          backdrop_path: '/dasEWdFNSobYvY8xWcfz3z02kTu.jpg',
          genre_ids: [28, 12, 14],
          id: 209112,
          media_type: 'movie',
          original_language: 'en',
          original_title: 'Batman v Superman: Dawn of Justice',
          overview:
            'Fearing the actions of a god-like Super Hero left unchecked, Gotham City’s own formidable, forceful vigilante takes on Metropolis’s most revered, modern-day savior, while the world wrestles with what sort of hero it really needs. And with Batman and Superman at war with one another, a new threat quickly arises, putting mankind in greater danger than it’s ever known before.',
          poster_path: '/5UsK3grJvtQrtzEgqNlDljJW96w.jpg',
          release_date: '2016-03-23',
          title: 'Batman v Superman: Dawn of Justice',
          video: false,
          vote_average: 5.9,
          vote_count: 14353,
        },
        {
          adult: false,
          backdrop_path: '/jorgjEk6a0bed6jdR5wu4S6ZvRm.jpg',
          genre_ids: [28, 12, 14, 878],
          id: 141052,
          media_type: 'movie',
          original_language: 'en',
          original_title: 'Justice League',
          overview:
            "Fuelled by his restored faith in humanity and inspired by Superman's selfless act, Bruce Wayne and Diana Prince assemble a team of metahumans consisting of Barry Allen, Arthur Curry and Victor Stone to face the catastrophic threat of Steppenwolf and the Parademons who are on the hunt for three Mother Boxes on Earth.",
          poster_path: '/eifGNCSDuxJeS1loAXil5bIGgvC.jpg',
          release_date: '2017-11-15',
          title: 'Justice League',
          video: false,
          vote_average: 6.2,
          vote_count: 10193,
        },
      ],
      known_for_department: 'Acting',
      name: 'Gal Gadot',
      popularity: 23.688,
      profile_path:
        'https://image.tmdb.org/t/p/h632/fysvehTvU6bE3JgxaOTRfvQJzJ4.jpg',
    },
    {
      adult: false,
      gender: 2,
      id: 2963,
      known_for: [
        {
          adult: false,
          backdrop_path: '/P4bGyJQF0shAcRku3I2perNUQR.jpg',
          genre_ids: [28, 80],
          id: 23483,
          media_type: 'movie',
          original_language: 'en',
          original_title: 'Kick-Ass',
          overview:
            'Dave Lizewski is an unnoticed high school student and comic book fan who one day decides to become a super-hero, even though he has no powers, training or meaningful reason to do so.',
          poster_path: '/GPiMXaDC2NdDIldLgtijHFTeKH.jpg',
          release_date: '2010-03-22',
          title: 'Kick-Ass',
          video: false,
          vote_average: 7.1,
          vote_count: 9198,
        },
        {
          adult: false,
          backdrop_path: '/7d6EY00g1c39SGZOoCJ5Py9nNth.jpg',
          genre_ids: [28, 12, 16, 878, 35],
          id: 324857,
          media_type: 'movie',
          original_language: 'en',
          original_title: 'Spider-Man: Into the Spider-Verse',
          overview:
            'Miles Morales is juggling his life between being a high school student and being a spider-man. When Wilson "Kingpin" Fisk uses a super collider, others from across the Spider-Verse are transported to this dimension.',
          poster_path: '/iiZZdoQBEYBv6id8su7ImL0oCbD.jpg',
          release_date: '2018-12-06',
          title: 'Spider-Man: Into the Spider-Verse',
          video: false,
          vote_average: 8.4,
          vote_count: 9050,
        },
        {
          adult: false,
          backdrop_path: '/bNgqt819qpHcszjCzLCG5y16ldF.jpg',
          genre_ids: [28, 12, 16, 35, 10751, 14],
          id: 49519,
          media_type: 'movie',
          original_language: 'en',
          original_title: 'The Croods',
          overview:
            'The prehistoric Croods family live in a particularly dangerous moment in time. Patriarch Grug, his mate Ugga, teenage daughter Eep, son Thunk, and feisty Gran gather food by day and huddle together in a cave at night. When a more evolved caveman named Guy arrives on the scene, Grug is distrustful, but it soon becomes apparent that Guy is correct about the impending destruction of their world.',
          poster_path: '/27zvjVOtOi5ped1HSlJKNsKXkFH.jpg',
          release_date: '2013-03-20',
          title: 'The Croods',
          video: false,
          vote_average: 6.9,
          vote_count: 5238,
        },
      ],
      known_for_department: 'Acting',
      name: 'Nicolas Cage',
      popularity: 23.394,
      profile_path:
        'https://image.tmdb.org/t/p/h632/y1RtezurZYveYkVNRht7CwEgSYY.jpg',
    },
    {
      adult: false,
      gender: 2,
      id: 6193,
      known_for: [
        {
          adult: false,
          backdrop_path: '/s3TBrRGB1iav7gFOCNx3H31MoES.jpg',
          genre_ids: [28, 878, 12],
          id: 27205,
          media_type: 'movie',
          original_language: 'en',
          original_title: 'Inception',
          overview:
            'Cobb, a skilled thief who commits corporate espionage by infiltrating the subconscious of his targets is offered a chance to regain his old life as payment for a task considered to be impossible: "inception", the implantation of another person\'s idea into a target\'s subconscious.',
          poster_path: '/9gk7adHYeDvHkCSEqAvQNLV5Uge.jpg',
          release_date: '2010-07-15',
          title: 'Inception',
          video: false,
          vote_average: 8.3,
          vote_count: 28541,
        },
        {
          adult: false,
          backdrop_path: '/s4cJQaj40SwMifUrrdtdOJsjnRO.jpg',
          genre_ids: [18, 37],
          id: 68718,
          media_type: 'movie',
          original_language: 'en',
          original_title: 'Django Unchained',
          overview:
            'With the help of a German bounty hunter, a freed slave sets out to rescue his wife from a brutal Mississippi plantation owner.',
          poster_path: '/4E4TTsCXVFyhBtYu9fKy0gIT3Ih.jpg',
          release_date: '2012-12-25',
          title: 'Django Unchained',
          video: false,
          vote_average: 8.1,
          vote_count: 20171,
        },
        {
          adult: false,
          backdrop_path: '/6VmFqApQRyZZzmiGOQq2C92jyvH.jpg',
          genre_ids: [18, 10749],
          id: 597,
          media_type: 'movie',
          original_language: 'en',
          original_title: 'Titanic',
          overview:
            "101-year-old Rose DeWitt Bukater tells the story of her life aboard the Titanic, 84 years later. A young Rose boards the ship with her mother and fiancé. Meanwhile, Jack Dawson and Fabrizio De Rossi win third-class tickets aboard the ship. Rose tells the whole story from Titanic's departure through to its death—on its first and last voyage—on April 15, 1912.",
          poster_path: '/9xjZS2rlVxm8SFx8kPC3aIGCOYQ.jpg',
          release_date: '1997-11-18',
          title: 'Titanic',
          video: false,
          vote_average: 7.9,
          vote_count: 18766,
        },
      ],
      known_for_department: 'Acting',
      name: 'Leonardo DiCaprio',
      popularity: 22.982,
      profile_path:
        'https://image.tmdb.org/t/p/h632/wo2hJpn04vbtmh0B9utCFdsQhxM.jpg',
    },
    {
      adult: false,
      gender: 2,
      id: 85,
      known_for: [
        {
          adult: false,
          backdrop_path: '/jOh79POQu4hyVIseUxdQxTW7vOf.jpg',
          genre_ids: [12, 14, 28],
          id: 22,
          media_type: 'movie',
          original_language: 'en',
          original_title:
            'Pirates of the Caribbean: The Curse of the Black Pearl',
          overview:
            "Jack Sparrow, a freewheeling 18th-century pirate, quarrels with a rival pirate bent on pillaging Port Royal. When the governor's daughter is kidnapped, Sparrow decides to help the girl's love save her.",
          poster_path: '/z8onk7LV9Mmw6zKz4hT6pzzvmvl.jpg',
          release_date: '2003-07-09',
          title: 'Pirates of the Caribbean: The Curse of the Black Pearl',
          video: false,
          vote_average: 7.7,
          vote_count: 15656,
        },
        {
          adult: false,
          backdrop_path: '/8Qsr8pvDL3s1jNZQ4HK1d1Xlvnh.jpg',
          genre_ids: [12, 14],
          id: 259316,
          media_type: 'movie',
          original_language: 'en',
          original_title: 'Fantastic Beasts and Where to Find Them',
          overview:
            'In 1926, Newt Scamander arrives at the Magical Congress of the United States of America with a magically expanded briefcase, which houses a number of dangerous creatures and their habitats. When the creatures escape from the briefcase, it sends the American wizarding authorities after Newt, and threatens to strain even further the state of magical and non-magical relations.',
          poster_path: '/fLsaFKExQt05yqjoAvKsmOMYvJR.jpg',
          release_date: '2016-11-16',
          title: 'Fantastic Beasts and Where to Find Them',
          video: false,
          vote_average: 7.4,
          vote_count: 15110,
        },
        {
          adult: false,
          backdrop_path: '/5gPPx16QWx071VAI1M0RAVKJ6tc.jpg',
          genre_ids: [12, 14, 28],
          id: 58,
          media_type: 'movie',
          original_language: 'en',
          original_title: "Pirates of the Caribbean: Dead Man's Chest",
          overview:
            'Captain Jack Sparrow works his way out of a blood debt with the ghostly Davy Jones to avoid eternal damnation.',
          poster_path: '/l3peI54mf6Z9EBSvS3hnRmOBbFT.jpg',
          release_date: '2006-07-06',
          title: "Pirates of the Caribbean: Dead Man's Chest",
          video: false,
          vote_average: 7.3,
          vote_count: 11959,
        },
      ],
      known_for_department: 'Acting',
      name: 'Johnny Depp',
      popularity: 22.864,
      profile_path:
        'https://image.tmdb.org/t/p/h632/ilPBHd3r3ahlipNQtjr4E3G04jJ.jpg',
    },
    {
      adult: false,
      gender: 2,
      id: 74568,
      known_for: [
        {
          adult: false,
          backdrop_path: '/kwUQFeFXOOpgloMgZaadhzkbTI4.jpg',
          genre_ids: [878, 28, 12],
          id: 24428,
          media_type: 'movie',
          original_language: 'en',
          original_title: 'The Avengers',
          overview:
            'When an unexpected enemy emerges and threatens global safety and security, Nick Fury, director of the international peacekeeping agency known as S.H.I.E.L.D., finds himself in need of a team to pull the world back from the brink of disaster. Spanning the globe, a daring recruitment effort begins!',
          poster_path: '/RYMX2wcKCBAr24UyPD7xwmjaTn.jpg',
          release_date: '2012-04-25',
          title: 'The Avengers',
          video: false,
          vote_average: 7.7,
          vote_count: 24146,
        },
        {
          adult: false,
          backdrop_path: '/lmZFxXgJE3vgrciwuDib0N8CfQo.jpg',
          genre_ids: [12, 28, 878],
          id: 299536,
          media_type: 'movie',
          original_language: 'en',
          original_title: 'Avengers: Infinity War',
          overview:
            'As the Avengers and their allies have continued to protect the world from threats too large for any one hero to handle, a new danger has emerged from the cosmic shadows: Thanos. A despot of intergalactic infamy, his goal is to collect all six Infinity Stones, artifacts of unimaginable power, and use them to inflict his twisted will on all of reality. Everything the Avengers have fought for has led up to this moment - the fate of Earth and existence itself has never been more uncertain.',
          poster_path: '/7WsyChQLEftFiDOVTGkv3hFpyyt.jpg',
          release_date: '2018-04-25',
          title: 'Avengers: Infinity War',
          video: false,
          vote_average: 8.3,
          vote_count: 21117,
        },
        {
          adult: false,
          backdrop_path: '/8i6ZDk97Vyh0jHohMG4vFeFuKJh.jpg',
          genre_ids: [28, 12, 878],
          id: 99861,
          media_type: 'movie',
          original_language: 'en',
          original_title: 'Avengers: Age of Ultron',
          overview:
            'When Tony Stark tries to jumpstart a dormant peacekeeping program, things go awry and Earth’s Mightiest Heroes are put to the ultimate test as the fate of the planet hangs in the balance. As the villainous Ultron emerges, it is up to The Avengers to stop him from enacting his terrible plans, and soon uneasy alliances and unexpected action pave the way for an epic and unique global adventure.',
          poster_path: '/4ssDuvEDkSArWEdyBl2X5EHvYKU.jpg',
          release_date: '2015-04-22',
          title: 'Avengers: Age of Ultron',
          video: false,
          vote_average: 7.3,
          vote_count: 17422,
        },
      ],
      known_for_department: 'Acting',
      name: 'Chris Hemsworth',
      popularity: 22.728,
      profile_path:
        'https://image.tmdb.org/t/p/h632/latNgwckKv3DtJIM8FK06T1GSYj.jpg',
    },
    {
      adult: false,
      gender: 2,
      id: 3223,
      known_for: [
        {
          adult: false,
          backdrop_path: '/kwUQFeFXOOpgloMgZaadhzkbTI4.jpg',
          genre_ids: [878, 28, 12],
          id: 24428,
          media_type: 'movie',
          original_language: 'en',
          original_title: 'The Avengers',
          overview:
            'When an unexpected enemy emerges and threatens global safety and security, Nick Fury, director of the international peacekeeping agency known as S.H.I.E.L.D., finds himself in need of a team to pull the world back from the brink of disaster. Spanning the globe, a daring recruitment effort begins!',
          poster_path: '/RYMX2wcKCBAr24UyPD7xwmjaTn.jpg',
          release_date: '2012-04-25',
          title: 'The Avengers',
          video: false,
          vote_average: 7.7,
          vote_count: 24146,
        },
        {
          adult: false,
          backdrop_path: '/lmZFxXgJE3vgrciwuDib0N8CfQo.jpg',
          genre_ids: [12, 28, 878],
          id: 299536,
          media_type: 'movie',
          original_language: 'en',
          original_title: 'Avengers: Infinity War',
          overview:
            'As the Avengers and their allies have continued to protect the world from threats too large for any one hero to handle, a new danger has emerged from the cosmic shadows: Thanos. A despot of intergalactic infamy, his goal is to collect all six Infinity Stones, artifacts of unimaginable power, and use them to inflict his twisted will on all of reality. Everything the Avengers have fought for has led up to this moment - the fate of Earth and existence itself has never been more uncertain.',
          poster_path: '/7WsyChQLEftFiDOVTGkv3hFpyyt.jpg',
          release_date: '2018-04-25',
          title: 'Avengers: Infinity War',
          video: false,
          vote_average: 8.3,
          vote_count: 21117,
        },
        {
          adult: false,
          backdrop_path: '/vbY95t58MDArtyUXUIb8Fx1dCry.jpg',
          genre_ids: [28, 878, 12],
          id: 1726,
          media_type: 'movie',
          original_language: 'en',
          original_title: 'Iron Man',
          overview:
            'After being held captive in an Afghan cave, billionaire engineer Tony Stark creates a unique weaponized suit of armor to fight evil.',
          poster_path: '/78lPtwv72eTNqFW9COBYI0dWDJa.jpg',
          release_date: '2008-04-30',
          title: 'Iron Man',
          video: false,
          vote_average: 7.6,
          vote_count: 20107,
        },
      ],
      known_for_department: 'Acting',
      name: 'Robert Downey Jr.',
      popularity: 22.626,
      profile_path:
        'https://image.tmdb.org/t/p/h632/5qHNjhtjMD4YWH3UP0rm4tKwxCL.jpg',
    },
    {
      adult: false,
      gender: 1,
      id: 132312,
      known_for: [
        {
          adult: false,
          backdrop_path: '/pM4xCEItOf6G3Uujvc6GttwWvtJ.jpg',
          genre_ids: [35],
          id: 227159,
          media_type: 'movie',
          original_language: 'en',
          original_title: 'Horrible Bosses 2',
          overview:
            "Dale, Kurt and Nick decide to start their own business but things don't go as planned because of a slick investor, prompting the trio to pull off a harebrained and misguided kidnapping scheme.",
          poster_path: '/boBOkwIqgrs8noxBUSDkkicKa4K.jpg',
          release_date: '2014-11-26',
          title: 'Horrible Bosses 2',
          video: false,
          vote_average: 6.2,
          vote_count: 3235,
        },
        {
          backdrop_path: '/oj81AUVQQ6hVgKTaXUnmia2zdpa.jpg',
          first_air_date: '2015-09-22',
          genre_ids: [9648, 80, 35, 18],
          id: 62046,
          media_type: 'tv',
          name: 'Scream Queens',
          origin_country: ['US'],
          original_language: 'en',
          original_name: 'Scream Queens',
          overview:
            'The super-charged comedy-horror series is a modern take on the classic whodunit with a killer cast. ',
          poster_path: '/yeayXZYSU8xdmC8i5g5jTdxeggp.jpg',
          vote_average: 8,
          vote_count: 989,
        },
        {
          backdrop_path: '/8vNQ3i2Xa3mrCKn6eq2ce5hhegT.jpg',
          first_air_date: '2019-10-06',
          genre_ids: [10759, 10765, 9648, 80],
          id: 89247,
          media_type: 'tv',
          name: 'Batwoman',
          origin_country: ['US'],
          original_language: 'en',
          original_name: 'Batwoman',
          overview:
            "Kate Kane, armed with a passion for social justice and a flair for speaking her mind, soars onto the streets of Gotham as Batwoman, an out lesbian and highly trained street fighter primed to snuff out the failing city's criminal resurgence. But don't call her a hero yet. In a city desperate for a savior, Kate must overcome her own demons before embracing the call to be Gotham's symbol of hope",
          poster_path: '/xjyEpcuDbB1jy0ehNQMBiO8KOdr.jpg',
          vote_average: 7.3,
          vote_count: 932,
        },
      ],
      known_for_department: 'Acting',
      name: 'Brianne Howey',
      popularity: 22.338,
      profile_path:
        'https://image.tmdb.org/t/p/h632/5TMOHWjWoK5xhzIgQkIGzpQ3cM7.jpg',
    },
    {
      adult: false,
      gender: 2,
      id: 287,
      known_for: [
        {
          adult: false,
          backdrop_path: '/52AfXWuXCHn3UjD17rBruA9f5qb.jpg',
          genre_ids: [18],
          id: 550,
          media_type: 'movie',
          original_language: 'en',
          original_title: 'Fight Club',
          overview:
            'A ticking-time-bomb insomniac and a slippery soap salesman channel primal male aggression into a shocking new form of therapy. Their concept catches on, with underground "fight clubs" forming in every town, until an eccentric gets in the way and ignites an out-of-control spiral toward oblivion.',
          poster_path: '/8kNruSfhk5IoE4eZOc4UpvDn6tq.jpg',
          release_date: '1999-10-15',
          title: 'Fight Club',
          video: false,
          vote_average: 8.4,
          vote_count: 21210,
        },
        {
          adult: false,
          backdrop_path: '/bPnPsyo09tLRnTOb7AlsBsgnbhP.jpg',
          genre_ids: [18, 28, 53, 10752],
          id: 16869,
          media_type: 'movie',
          original_language: 'en',
          original_title: 'Inglourious Basterds',
          overview:
            'In Nazi-occupied France during World War II, a group of Jewish-American soldiers known as "The Basterds" are chosen specifically to spread fear throughout the Third Reich by scalping and brutally killing Nazis. The Basterds, lead by Lt. Aldo Raine soon cross paths with a French-Jewish teenage girl who runs a movie theater in Paris which is targeted by the soldiers.',
          poster_path: '/7sfbEnaARXDDhKm0CZ7D7uc2sbo.jpg',
          release_date: '2009-08-18',
          title: 'Inglourious Basterds',
          video: false,
          vote_average: 8.2,
          vote_count: 16398,
        },
        {
          adult: false,
          backdrop_path: '/i5H7zusQGsysGQ8i6P361Vnr0n2.jpg',
          genre_ids: [80, 9648, 53],
          id: 807,
          media_type: 'movie',
          original_language: 'en',
          original_title: 'Se7en',
          overview:
            'Two homicide detectives are on a desperate hunt for a serial killer whose crimes are based on the "seven deadly sins" in this dark and haunting film that takes viewers from the tortured remains of one victim to the next. The seasoned Det. Sommerset researches each sin in an effort to get inside the killer\'s mind, while his novice partner, Mills, scoffs at his efforts to unravel the case.',
          poster_path: '/69Sns8WoET6CfaYlIkHbla4l7nC.jpg',
          release_date: '1995-09-22',
          title: 'Se7en',
          video: false,
          vote_average: 8.3,
          vote_count: 14747,
        },
      ],
      known_for_department: 'Acting',
      name: 'Brad Pitt',
      popularity: 22,
      profile_path:
        'https://image.tmdb.org/t/p/h632/ajNaPmXVVMJFg9GWmu6MJzTaXdV.jpg',
    },
    {
      adult: false,
      gender: 1,
      id: 10882,
      known_for: [
        {
          adult: false,
          backdrop_path: '/znsgNAo52yCTtkHfmF1N0vIfj6D.jpg',
          genre_ids: [9648, 53, 18],
          id: 210577,
          media_type: 'movie',
          original_language: 'en',
          original_title: 'Gone Girl',
          overview:
            "With his wife's disappearance having become the focus of an intense media circus, a man sees the spotlight turned on him when it's suspected that he may not be innocent.",
          poster_path: '/qymaJhucquUwjpb8oiqynMeXnID.jpg',
          release_date: '2014-10-01',
          title: 'Gone Girl',
          video: false,
          vote_average: 7.9,
          vote_count: 13922,
        },
        {
          adult: false,
          backdrop_path: '/yBq4jWZLaEJIssuVx2fAysEwJnt.jpg',
          genre_ids: [18, 10749],
          id: 4348,
          media_type: 'movie',
          original_language: 'en',
          original_title: 'Pride & Prejudice',
          overview:
            "A story of love and life among the landed English gentry during the Georgian era. Mr. Bennet is a gentleman living in Hertfordshire with his overbearing wife and five daughters, but if he dies their house will be inherited by a distant cousin whom they have never met, so the family's future happiness and security is dependent on the daughters making good marriages.",
          poster_path: '/sZEXhhnEKh9hjzoiIi9XgHGqtYm.jpg',
          release_date: '2005-09-16',
          title: 'Pride & Prejudice',
          video: false,
          vote_average: 8.1,
          vote_count: 5538,
        },
        {
          adult: false,
          backdrop_path: '/k7h4RNAarfOrF2r2YMN0P2FQSr4.jpg',
          genre_ids: [80, 18, 53, 28],
          id: 75780,
          media_type: 'movie',
          original_language: 'en',
          original_title: 'Jack Reacher',
          overview:
            'When a gunman takes five lives with six shots, all evidence points to the suspect in custody. On interrogation, the suspect offers up a single note: "Get Jack Reacher!" So begins an extraordinary chase for the truth, pitting Jack Reacher against an unexpected enemy, with a skill for violence and a secret to keep.',
          poster_path: '/zlyhKMi2aLk25nOHnNm43MpZMtQ.jpg',
          release_date: '2012-12-20',
          title: 'Jack Reacher',
          video: false,
          vote_average: 6.5,
          vote_count: 5121,
        },
      ],
      known_for_department: 'Acting',
      name: 'Rosamund Pike',
      popularity: 21.371,
      profile_path:
        'https://image.tmdb.org/t/p/h632/s9i4XoHTgtskbralOtnraEueU2M.jpg',
    },
  ],
  total_pages: 500,
  total_results: 10000,
};
