export const ROUTE_NAMES = {
  root: '/',
  movies: 'movies',
  movie: 'movie',
  credits: `credits`,
  tvShows: 'tvShows',
  tvShow: 'tvShow',
  people: 'people',
  person: 'person',
  videos: 'videos',
  seasons: 'seasons',
  season: 'season',
  episode: 'episode',
  search: 'search',
};
